export const buildings: { buildingName: string }[] = [
  { buildingName: 'barracks' },
  { buildingName: 'dock' },
  { buildingName: 'siege workshop' },
  { buildingName: 'farm' },
  { buildingName: 'mill' },
  { buildingName: 'house' },
  { buildingName: 'town center' },
  { buildingName: 'palisade wall' },
  { buildingName: 'watch tower' },
  { buildingName: 'castle' },
  { buildingName: 'market' },
  { buildingName: 'archery range' },
  { buildingName: 'stable' },
  { buildingName: 'blacksmith' },
  { buildingName: 'monastery' },
  { buildingName: 'stone wall' },
  { buildingName: 'fortified wall' },
  { buildingName: 'fish trap' },
  { buildingName: 'university' },
  { buildingName: 'guard tower' },
  { buildingName: 'keep' },
  { buildingName: 'bombard tower' },
  { buildingName: 'wonder' },
  { buildingName: 'gate' },
  { buildingName: 'lumber camp' },
  { buildingName: 'mining camp' },
  { buildingName: 'outpost' },
  { buildingName: 'palisade gate' },
  { buildingName: 'feitoria' },
  { buildingName: 'harbor' },
  { buildingName: 'krepost' },
  { buildingName: 'donjon' },
  { buildingName: 'folwark' },
  { buildingName: 'caravanserai' },
];
