import { CreateCivDto } from '../../src/civ/dto/create-civ.dto';

export const civs: CreateCivDto[] = [
  { civName: 'Aztecs' },
  { civName: 'Bengalis' },
  { civName: 'Berbers' },
  { civName: 'Bohemians' },
  { civName: 'Britons' },
  { civName: 'Bulgarians' },
  { civName: 'Burgundians' },
  { civName: 'Burmese' },
  { civName: 'Byzantines' },
  { civName: 'Celts' },
  { civName: 'Chinese' },
  { civName: 'Cumans' },
  { civName: 'Dravidians' },
  { civName: 'Ethiopians' },
  { civName: 'Franks' },
  { civName: 'Goths' },
  { civName: 'Gurjaras' },
  { civName: 'Hindustanis' },
  { civName: 'Huns' },
  { civName: 'Incas' },
  { civName: 'Italians' },
  { civName: 'Japanese' },
  { civName: 'Khmer' },
  { civName: 'Koreans' },
  { civName: 'Lithuanians' },
  { civName: 'Magyars' },
  { civName: 'Malay' },
  { civName: 'Malians' },
  { civName: 'Mayans' },
  { civName: 'Mongols' },
  { civName: 'Persians' },
  { civName: 'Poles' },
  { civName: 'Portuguese' },
  { civName: 'Saracens' },
  { civName: 'Sicilians' },
  { civName: 'Slavs' },
  { civName: 'Spanish' },
  { civName: 'Tatars' },
  { civName: 'Teutons' },
  { civName: 'Turks' },
  { civName: 'Vietnamese' },
  { civName: 'Vikings' },
];
