export const techs: { techName: string }[] = [
  { techName: 'crossbowman upgrade' },
  { techName: 'arbalaster upgrade' },
  { techName: 'elite skirmisher upgrade' },
  { techName: 'imperial skirmisher upgrade' },
  { techName: 'havey cavalry upgrade' },
  { techName: 'elite elephant archer upgrade' },
  { techName: 'elite genitour upgrade' },
  { techName: 'thumb ring' },
  { techName: 'parthian tactics' },
  { techName: 'man-at-arms upgrade' },
  { techName: 'long swordsman upgrade' },
  { techName: 'two-handed swordsman upgrade' },
  { techName: 'champion upgrade' },
  { techName: 'pikeman upgrade' },
  { techName: 'halberdier upgrade' },
  { techName: 'eagle warrior upgrade' },
  { techName: 'elite eagle warrior upgrade' },
  { techName: 'supplies' },
  { techName: 'squires' },
  { techName: 'arson' },
  { techName: 'light cavalry upgrade' },
  { techName: 'hussar upgrade' },
  { techName: 'winged hussar upgrade' },
  { techName: 'elite shrivamsha rider upgrade' },
  { techName: 'heavy camel rider upgrade' },
  { techName: 'imperial camel rider upgrade' },
  { techName: 'cavalier upgrade' },
  { techName: 'paladin upgrade' },
  { techName: 'elite battle elephant upgrade' },
  { techName: 'elite steppe lancer upgrade' },
  { techName: 'bloodlines' },
  { techName: 'husabandry' },
  { techName: 'capped ram upgrade' },
  { techName: 'siege ram upgrade' },
  { techName: 'siege elephant upgrade' },
  { techName: 'onager upgrade' },
  { techName: 'siege onager upgrade' },
  { techName: 'heavy scropion upgrade' },
  { techName: 'houfnice upgrade' },
  { techName: 'padded archer armor' },
  { techName: 'leather archer armor' },
  { techName: 'ring archer armor' },
  { techName: 'fletching' },
  { techName: 'bodkin arrow' },
  { techName: 'bracer' },
  { techName: 'forging' },
  { techName: 'iron casting' },
  { techName: 'blast furnace' },
  { techName: 'scale barding armor' },
  { techName: 'chain barding armor' },
  { techName: 'plate barding armor' },
  { techName: 'scale mail armor' },
  { techName: 'chain mail armor' },
  { techName: 'plate mail armor' },
  { techName: 'war galley upgrade' },
  { techName: 'gillnets' },
  { techName: 'fast fire ship upgrade' },
  { techName: 'heavy demolition ship upgrade' },
  { techName: 'galleon upgrade' },
  { techName: 'elite cannon galleon upgrade' },
  { techName: 'elite turtle ship upgrade' },
  { techName: 'elite longboat upgrade' },
  { techName: 'elite caravael upgrade' },
  { techName: 'careening' },
  { techName: 'dry dock' },
  { techName: 'shipwright' },
  { techName: 'masonry' },
  { techName: 'architecture' },
  { techName: 'fortified wall' },
  { techName: 'ballistics' },
  { techName: 'guard tower' },
  { techName: 'heated shot' },
  { techName: 'murder holes' },
  { techName: 'treadmill crane' },
  { techName: 'chemistry' },
  { techName: 'siege engineers' },
  { techName: 'keep' },
  { techName: 'arrowslits' },
  { techName: 'bombard tower' },
  { techName: 'hoardings' },
  { techName: 'sappers' },
  { techName: 'conscription' },
  { techName: 'spies/treason' },
  { techName: 'redemption' },
  { techName: 'atonment' },
  { techName: 'herbal medicine' },
  { techName: 'heresy' },
  { techName: 'sanctity' },
  { techName: 'fervor' },
  { techName: 'faith' },
  { techName: 'illumination' },
  { techName: 'block printing' },
  { techName: 'theocracy' },
  { techName: 'feudal age' },
  { techName: 'castle age' },
  { techName: 'imperial age' },
  { techName: 'loom' },
  { techName: 'wheelbarrow' },
  { techName: 'hand cart' },
  { techName: 'double-bit axe' },
  { techName: 'bow saw' },
  { techName: 'two-man saw' },
  { techName: 'horse collar' },
  { techName: 'heavy plow' },
  { techName: 'crop rotation' },
  { techName: 'gold mining' },
  { techName: 'gold shaft mining' },
  { techName: 'stone mining' },
  { techName: 'stone shaft mining' },
  { techName: 'coinage' },
  { techName: 'banking' },
  { techName: 'caravan' },
  { techName: 'guilds' },
  { techName: 'atlatl' },
  { techName: 'garland wars' },
  { techName: 'paiks' },
  { techName: 'mahayana' },
  { techName: 'kasbah' },
  { techName: 'maghrebi camels' },
  { techName: 'wagenburg tactics' },
  { techName: 'hussite reforms' },
  { techName: 'yeomen' },
  { techName: 'warwolf' },
  { techName: 'stirrups' },
  { techName: 'bagains' },
  { techName: 'burgundian vineyards' },
  { techName: 'flemish revolution' },
  { techName: 'howdah' },
  { techName: 'manipur cavalry' },
  { techName: 'greek fire' },
  { techName: 'logistica' },
  { techName: 'stronghold' },
  { techName: 'furor celtica' },
  { techName: 'great wall' },
  { techName: 'rocketry' },
  { techName: 'steppe husbandry' },
  { techName: 'cuman mercenaries' },
  { techName: 'medical corps' },
  { techName: 'wootz steel' },
  { techName: 'royal heirs' },
  { techName: 'torsion engines' },
  { techName: 'bearded axe' },
  { techName: 'chivalry' },
  { techName: 'anarchy' },
  { techName: 'perfusion' },
  { techName: 'kshatriyas' },
  { techName: 'frontier guards' },
  { techName: 'grand trunk road' },
  { techName: 'shatagni' },
  { techName: 'marauders' },
  { techName: 'atheism' },
  { techName: 'andean sling' },
  { techName: 'fabric sheilds' },
  { techName: 'pavise' },
  { techName: 'silk road' },
  { techName: 'yasama' },
  { techName: 'kataparuto' },
  { techName: 'tusk swords' },
  { techName: 'double crossbow' },
  { techName: 'eupseong' },
  { techName: 'shinkichon' },
  { techName: 'hill forts' },
  { techName: 'tower shields' },
  { techName: 'corvinian army' },
  { techName: 'recurve bow' },
  { techName: 'thalassocracy' },
  { techName: 'forced levy' },
  { techName: 'tigui' },
  { techName: 'farimba' },
  { techName: "hul'che javelineers" },
  { techName: 'el dorado' },
  { techName: 'nomads' },
  { techName: 'drill' },
  { techName: 'kamandaran' },
  { techName: 'mahouts' },
  { techName: 'szlachta prvilieges' },
  { techName: 'lechitic legacy' },
  { techName: 'carrack' },
  { techName: 'arquebus' },
  { techName: 'zealotry' },
  { techName: 'counterweights' },
  { techName: 'first crusade' },
  { techName: 'hauberk' },
  { techName: 'detinets' },
  { techName: 'druzhina' },
  { techName: 'inquisition' },
  { techName: 'supremacy' },
  { techName: 'silk armor' },
  { techName: 'timurid siegecraft' },
  { techName: 'ironclad' },
  { techName: 'crenellations' },
  { techName: 'sipahi' },
  { techName: 'artillery' },
  { techName: 'chatras' },
  { techName: 'paper money' },
  { techName: 'chietains' },
  { techName: 'berserkergang' },
];
