export const techs: { techName: string }[] = [
  { techName: 'yeomen' },
  { techName: 'el dorado' },
  { techName: 'furor celtica' },
  { techName: 'drill' },
  { techName: 'mahouts' },
  { techName: 'town watch' },
  { techName: 'zealotry' },
  { techName: 'artillery' },
  { techName: 'crenellations' },
  { techName: 'crop rotation' },
  { techName: 'heavy plow' },
  { techName: 'horse collar' },
  { techName: 'guilds' },
  { techName: 'anarchy' },
  { techName: 'banking' },
  { techName: 'cartography' },
  { techName: 'atheism' },
  { techName: 'loom' },
  { techName: 'coinage' },
  { techName: 'garland wars' },
  { techName: 'husbandry' },
  { techName: 'faith' },
  { techName: 'chemistry' },
  { techName: 'caravan' },
  { techName: 'berserkergang' },
  { techName: 'masonry' },
  { techName: 'architecture' },
  { techName: 'rocketry' },
  { techName: 'treadmill crane' },
  { techName: 'gold mining' },
  { techName: 'kataparuto' },
  { techName: 'logistica' },
  { techName: 'keep' },
  { techName: 'bombard tower' },
  { techName: 'gillnets' },
  { techName: 'forging' },
  { techName: 'iron casting' },
  { techName: 'scale mail armor' },
  { techName: 'blast furnace' },
  { techName: 'chain mail armor' },
  { techName: 'plate mail armor' },
  { techName: 'plate barding armor' },
  { techName: 'scale barding armor' },
  { techName: 'chain barding armor' },
  { techName: 'bearded axe' },
  { techName: 'tracking' },
  { techName: 'ballistics' },
  { techName: 'feudal age' },
  { techName: 'castle age' },
  { techName: 'imperial age' },
  { techName: 'guard tower' },
  { techName: 'gold shaft mining' },
  { techName: 'fortified wall' },
  { techName: 'fletching' },
  { techName: 'bodkin arrow' },
  { techName: 'bracer' },
  { techName: 'double-bit axe' },
  { techName: 'bow saw' },
  { techName: 'padded archer armor' },
  { techName: 'leather archer armor' },
  { techName: 'wheelbarrow' },
  { techName: 'squires' },
  { techName: 'ring archer armor' },
  { techName: 'two-man saw' },
  { techName: 'block printing' },
  { techName: 'sanctity' },
  { techName: 'illumination' },
  { techName: 'hand cart' },
  { techName: 'fervor' },
  { techName: 'stone mining' },
  { techName: 'stone shaft mining' },
  { techName: 'town patrol' },
  { techName: 'conscription' },
  { techName: 'redemption' },
  { techName: 'atonement' },
  { techName: 'sappers' },
  { techName: 'murder holes' },
  { techName: 'shipwright' },
  { techName: 'careening' },
  { techName: 'dry dock' },
  { techName: 'siege engineers' },
  { techName: 'hoardings' },
  { techName: 'heated shot' },
  { techName: 'spies - treason' },
  { techName: 'bloodlines' },
  { techName: 'parthian tactics' },
  { techName: 'thumb ring' },
  { techName: 'theocracy' },
  { techName: 'heresy' },
  { techName: 'supremacy' },
  { techName: 'herbal medicine' },
  { techName: 'shinkichon' },
  { techName: 'counterweights' },
  { techName: 'detinets' },
  { techName: 'perfusion' },
  { techName: 'atlatl' },
  { techName: 'warwolf' },
  { techName: 'great wall' },
  { techName: 'chieftains' },
  { techName: 'greek fire' },
  { techName: 'stronghold' },
  { techName: 'marauders' },
  { techName: 'yasama' },
  { techName: "hul'che javelineers" },
  { techName: 'eupseong' },
  { techName: 'nomads' },
  { techName: 'kamandaran' },
  { techName: 'ironclad' },
  { techName: 'sipahi' },
  { techName: 'inquisition' },
  { techName: 'chivalry' },
  { techName: 'pavise' },
  { techName: 'silk road' },
  { techName: 'grand trunk road' },
  { techName: 'shatagni' },
  { techName: 'druzhina' },
  { techName: 'corvinian army' },
  { techName: 'recurve bow' },
  { techName: 'andean sling' },
  { techName: 'fabric shields' },
  { techName: 'carrack' },
  { techName: 'arquebus' },
  { techName: 'royal heirs' },
  { techName: 'torsion engines' },
  { techName: 'tigui' },
  { techName: 'farimba' },
  { techName: 'kasbah' },
  { techName: 'maghrebi camels' },
  { techName: 'arson' },
  { techName: 'arrowslits' },
  { techName: 'tusk swords' },
  { techName: 'double crossbow' },
  { techName: 'thalassocracy' },
  { techName: 'forced levy' },
  { techName: 'howdah' },
  { techName: 'manipur cavalry' },
  { techName: 'chatras' },
  { techName: 'paper money' },
  { techName: 'stirrups' },
  { techName: 'bagains' },
  { techName: 'silk armor' },
  { techName: 'timurid siegecraft' },
  { techName: 'steppe husbandry' },
  { techName: 'cuman mercenaries' },
  { techName: 'hill forts' },
  { techName: 'tower shields' },
  { techName: 'supplies' },
  { techName: 'burgundian vineyards' },
  { techName: 'flemish revolution' },
  { techName: 'first crusade' },
  { techName: 'hauberk' },
  { techName: 'szlachta privileges' },
  { techName: 'lechitic legacy' },
  { techName: 'wagenburg tactics' },
  { techName: 'hussite reforms' },
  { techName: 'medical corps' },
  { techName: 'wootz steel' },
  { techName: 'paiks' },
  { techName: 'mahayana' },
  { techName: 'kshatriyas' },
  { techName: 'frontier guards' },
];
