export const units: { unitName: string }[] = [
  { unitName: 'archer' },
  { unitName: 'crossbowman' },
  { unitName: 'arbalaster' },
  { unitName: 'skirmisher' },
  { unitName: 'elite skirmisher' },
  { unitName: 'imperial skirmisher' },
  { unitName: 'slinger' },
  { unitName: 'hand cannonneer' },
  { unitName: 'cavalry archer' },
  { unitName: 'heavy cavalry archer' },
  { unitName: 'elephant archer' },
  { unitName: 'elite elephant archer' },
  { unitName: 'genitour' },
  { unitName: 'elite genitour' },
  { unitName: 'militia' },
  { unitName: 'man-at-arms' },
  { unitName: 'long swordsman' },
  { unitName: 'two-handed swordsman' },
  { unitName: 'champion' },
  { unitName: 'spearman' },
  { unitName: 'pikeman' },
  { unitName: 'halberdier' },
  { unitName: 'eagle scout' },
  { unitName: 'eagle warrior' },
  { unitName: 'elite eagle warrior' },
  { unitName: 'condottiero' },
  { unitName: 'scout cavalry' },
  { unitName: 'light cavalry' },
  { unitName: 'hussar' },
  { unitName: 'winged hussar' },
  { unitName: 'shrivamsha rider' },
  { unitName: 'elite shrivamsha rider' },
  { unitName: 'camel scout' },
  { unitName: 'camel rider' },
  { unitName: 'heavy camel rider' },
  { unitName: 'imperial camel rider' },
  { unitName: 'knight' },
  { unitName: 'cavalier' },
  { unitName: 'paladin' },
  { unitName: 'battle elephant' },
  { unitName: 'elite battle elephant' },
  { unitName: 'steppe lancer' },
  { unitName: 'elite steppe lancer' },
  { unitName: 'xolotl warrior' },
  { unitName: 'battering ram' },
  { unitName: 'capped ram' },
  { unitName: 'siege ram' },
  { unitName: 'armored elephant' },
  { unitName: 'siege elephant' },
  { unitName: 'mangonel' },
  { unitName: 'onager' },
  { unitName: 'siege onager' },
  { unitName: 'scorpion' },
  { unitName: 'heavy scorpion' },
  { unitName: 'siege tower' },
  { unitName: 'bombard cannon' },
  { unitName: 'houfnice' },
  { unitName: 'fishing ship' },
  { unitName: 'transport ship' },
  { unitName: 'trade cog' },
  { unitName: 'fire galley' },
  { unitName: 'fire ship' },
  { unitName: 'fast fire ship' },
  { unitName: 'demolition raft' },
  { unitName: 'demolition ship' },
  { unitName: 'heavy demolition ship' },
  { unitName: 'galley' },
  { unitName: 'war galley' },
  { unitName: 'galleon' },
  { unitName: 'cannon galleon' },
  { unitName: 'elite cannon galleon' },
  { unitName: 'turtle ship' },
  { unitName: 'elite turtle ship' },
  { unitName: 'longboat' },
  { unitName: 'elite longboat' },
  { unitName: 'caravel' },
  { unitName: 'elite caravel' },
  { unitName: 'thirisadai' },
  { unitName: 'petard' },
  { unitName: 'trebuchet' },
  { unitName: 'monk' },
  { unitName: 'missionary' },
  { unitName: 'villager' },
  { unitName: 'trade cart' },
  { unitName: 'flemish militia' },
  { unitName: 'jaguar warrior' },
  { unitName: 'elite jaguar warrior' },
  { unitName: 'ratha' },
  { unitName: 'elite ratha' },
  { unitName: 'camel archer' },
  { unitName: 'elite camel archer' },
  { unitName: 'hussite wagon' },
  { unitName: 'elite hussite wagon' },
  { unitName: 'longbowman' },
  { unitName: 'elite longbowman' },
  { unitName: 'konnik' },
  { unitName: 'elite konnik' },
  { unitName: 'coustillier' },
  { unitName: 'elite coustillier' },
  { unitName: 'arambai' },
  { unitName: 'elite arambai' },
  { unitName: 'cataphract' },
  { unitName: 'elite cataphract' },
  { unitName: 'woad raider' },
  { unitName: 'elite woad raider' },
  { unitName: 'cho ku nu' },
  { unitName: 'elite cho ku nu' },
  { unitName: 'kipchak' },
  { unitName: 'elite kipchak' },
  { unitName: 'urumi swordsman' },
  { unitName: 'elite urumi swordsman' },
  { unitName: 'shotel warrior' },
  { unitName: 'elite shotel warrior' },
  { unitName: 'throwing axeman' },
  { unitName: 'elite throwing axeman' },
  { unitName: 'huskarl' },
  { unitName: 'elite huskarl' },
  { unitName: 'chakram thrower' },
  { unitName: 'elite chakram thrower' },
  { unitName: 'ghulam' },
  { unitName: 'elite ghulam' },
  { unitName: 'tarkan' },
  { unitName: 'elite tarkan' },
  { unitName: 'kamayuk' },
  { unitName: 'elite kamayuk' },
  { unitName: 'genoese crossbowman' },
  { unitName: 'elite genoese crossbowman' },
  { unitName: 'samurai' },
  { unitName: 'elite samurai' },
  { unitName: 'ballista elephant' },
  { unitName: 'elite ballista elephant' },
  { unitName: 'war wagon' },
  { unitName: 'elite war wagon' },
  { unitName: 'leitis' },
  { unitName: 'elite leitis' },
  { unitName: 'magyar huszar' },
  { unitName: 'elite magyar huszar' },
  { unitName: 'karambit warrior' },
  { unitName: 'elite karambit warrior' },
  { unitName: 'gbeto' },
  { unitName: 'elite gbeto' },
  { unitName: 'plumed archer' },
  { unitName: 'elite plumed archer' },
  { unitName: 'mangudai' },
  { unitName: 'elite mangudai' },
  { unitName: 'war elephant' },
  { unitName: 'elite war elephant' },
  { unitName: 'obuch' },
  { unitName: 'elite obuch' },
  { unitName: 'organ gun' },
  { unitName: 'elite organ gun' },
  { unitName: 'mameluke' },
  { unitName: 'elite mameluke' },
  { unitName: 'serjeant' },
  { unitName: 'elite serjeant' },
  { unitName: 'boyar' },
  { unitName: 'elite boyar' },
  { unitName: 'conquistador' },
  { unitName: 'elite conquistador' },
  { unitName: 'keshik' },
  { unitName: 'elite keshik' },
  { unitName: 'flaming camel' },
  { unitName: 'teutonic knight' },
  { unitName: 'elite teutonic knight' },
  { unitName: 'janissary' },
  { unitName: 'elite janissary' },
  { unitName: 'rattan archer' },
  { unitName: 'elite rattan archer' },
  { unitName: 'berserk' },
  { unitName: 'elite berserk' },
];
